### ISSUE TITLE
pgx in Docker

### ISSUE THREAD

**Issue by virtumonde** [jackc/pgx#837]
I am trying to connect to a Postgres database using pgx. Both the database and the golang app that uses pgx are located in a separate Docker container. After running this line

```
Pool, err = pgxpool.Connect(context.Background(), "postgres://postgres:postgres@postgres:5432/postgres")
```
I receive
```
2020/09/25 17:43:35 failed to connect to `host=database user=terminus database=terminus`: hostname resolving error (lookup database on 192.168.65.1:53: no such host)
```
I know that the database works as I was able to connect with DBeaver. Is there a chance that the problem is in pgx? Here is my ```docker-compose```file:
```
version: "3.8"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - go_develop
  envoy:
    build: ./envoy
    restart: always
    networks:
      - go_develop
  server:
    build: ./server
    depends_on:
      - postgres
    ports:
      - "2302:2302"
      - "80:80"
    restart: always
    networks:
      - go_develop
networks:
  go_develop:
    driver: bridge
```
